name: interstellar

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.2.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Is a transitive dependency from above, but cannot be updated out of step 
  # with the SDK.
  intl: ^0.18.1

  flutter_markdown: ^0.6.18+2
  http: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  oauth2: ^2.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  youtube_explode_dart: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
